//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_system3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_cateogry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cateogry()
        {
            this.tbl_product = new HashSet<tbl_product>();
        }
    
        public int cat_id { get; set; }
        [Required(ErrorMessage ="enter category name")]
        public string cat_name { get; set; }
        public string cat_image { get; set; }
        [Required(ErrorMessage ="enter status if 0 its mean category not available , if 1 it is available ")]
        public Nullable<int> cat_status { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_product> tbl_product { get; set; }
    }
}
