//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_system3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_order()
        {
            this.tbl_invoice = new HashSet<tbl_invoice>();
        }
    
        public int ord_id { get; set; }
        public string ord_productname { get; set; }
        public Nullable<double> ord_amount { get; set; }
        public Nullable<int> ord_quantity { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> sci_id_fk { get; set; }
        public Nullable<int> med_id_fk { get; set; }
        public Nullable<int> edu_id_fk { get; set; }
        public Nullable<int> bu_id_fk { get; set; }
        public Nullable<int> u_id_fk { get; set; }
        public Nullable<int> pr_id_fk { get; set; }
        public string buyers_name { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_bu_appl tbl_bu_appl { get; set; }
        public virtual tbl_edu_appl tbl_edu_appl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        public virtual tbl_med_appl tbl_med_appl { get; set; }
        public virtual tbl_sci_appl tbl_sci_appl { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
