//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_system3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_contact
    {
        public int contact_id { get; set; }
        [Required(ErrorMessage ="enter first name")]
        public string first_name { get; set; }
        [Required(ErrorMessage = "enter last name")]
        public string last_name { get; set; }
        [Required(ErrorMessage = "enter email id")]
        public string email_id { get; set; }
        [Required(ErrorMessage = "enter message")]
        public string sms { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> u_id_fk { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
