//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_system3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_feedback
    {
        public int feed_id { get; set; }
        public string feedback { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string contact_number { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> bu_id_fk { get; set; }
        public Nullable<int> u_id_fk { get; set; }
        public Nullable<int> gen_id_fk { get; set; }
        public Nullable<int> cnt_id_fk { get; set; }
        public string sugestion { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_bu_appl tbl_bu_appl { get; set; }
        public virtual tbl_country tbl_country { get; set; }
        public virtual tbl_gendar tbl_gendar { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
