//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_system3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int inv_id { get; set; }
        public Nullable<double> total_bill { get; set; }
        public Nullable<System.DateTime> inv_date { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> sci_id_fk { get; set; }
        public Nullable<int> med_id_fk { get; set; }
        public Nullable<int> edu_id_fk { get; set; }
        public Nullable<int> bu_id_fk { get; set; }
        public Nullable<int> u_id_fk { get; set; }
        public Nullable<int> ord_id_fk { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_bu_appl tbl_bu_appl { get; set; }
        public virtual tbl_edu_appl tbl_edu_appl { get; set; }
        public virtual tbl_med_appl tbl_med_appl { get; set; }
        public virtual tbl_order tbl_order { get; set; }
        public virtual tbl_sci_appl tbl_sci_appl { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
