//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_system3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user()
        {
            this.tbl_feedback = new HashSet<tbl_feedback>();
            this.tbl_contact = new HashSet<tbl_contact>();
            this.tbl_invoice = new HashSet<tbl_invoice>();
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int u_id { get; set; }
        [Required(ErrorMessage ="entre user name")]
        public string u_name { get; set; }
        [Required(ErrorMessage ="enter email id")]
        public string u_email { get; set; }
        [Required(ErrorMessage = "enter password")]
        public string u_password { get; set; }
        [Required(ErrorMessage = "enter contact number")]
        public string u_contact { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> sci_id_fk { get; set; }
        public Nullable<int> med_id_fk { get; set; }
        public Nullable<int> edu_id_fk { get; set; }
        public Nullable<int> bu_id_fk { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_bu_appl tbl_bu_appl { get; set; }
        public virtual tbl_edu_appl tbl_edu_appl { get; set; }
        public virtual tbl_med_appl tbl_med_appl { get; set; }
        public virtual tbl_sci_appl tbl_sci_appl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_feedback> tbl_feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_contact> tbl_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
